### ISSUE TITLE
Tool overwrites.

### ISSUE THREAD

**Issue by SummitSummit** [MarioAndWeegee3/Tool-Builder#1]
I can't make a vanilla stone shovel.  It always just makes a Tool Builder version of the shovel.  This makes it so I can't make a paxel from another mod.  The axe and the pickaxe, when made with sticks, make the vanilla tool, but the shovel doesn't. 
MC 1.14.4
Toolbuilder 1.4.0

**Comment by RetroAech** [comment]
This! I am having the same issue and would love a fix! Also my crash log tells me theres a misspelling. https://imgur.com/a/WDpnJqA

Not being able to repair my better enchanted weapons is a huge issue. Cant use Tool builder to repair vanilla tools. Big ouch.

**Comment by MarioAndWeegee3** [comment]
Fixed in 1.5.0+; change the config option for crafting the tools with sticks.
