### ISSUE TITLE
toolbuilder-1.16.0 [fabric -1.15.1] crash on load

### ISSUE THREAD

**Issue by SDUBZ** [MarioAndWeegee3/Tool-Builder#12]
toolbuilder-1.16.0.jar
fabric:1.15.1-175

crash:
https://paste.ee/p/Q3oci

**Comment by daybreak3831** [comment]
I don't know if this applies to you, but I'm in conflict with the mode shulkercharm and I'm giving up shulkercharm and using it normally. This article was written by a translator.

**Comment by LemmaEOF** [comment]
This isn't ShulkerCharm. ToolBuilder uses a custom resource pack adder, and Mojang fucked over people who want to do that in 1.15+ by putting all the initialization for `MinecraftClient` in the constructor. Fabric API will have a hook for adding resource packs soon.

**Comment by MarioAndWeegee3** [comment]
Fixed in 1.16.1
