### ISSUE TITLE
Crash on load 1.16.2

### ISSUE THREAD

**Issue by ClaudiusMinimus** [MarioAndWeegee3/Tool-Builder#14]
I'm putting together a modpack and when I try to enable Tool Builder 1.15.3, 1.16.1, or 1.16.2 it crashes. Pack runs fine with Tool Builder disabled.

**Crash Log**
https://paste.ee/p/WIpBa

- Minecraft Version ID: 1.15.1
- 	Operating System: Windows 10 (amd64) version 10.0
- 	Java Version: 1.8.0_231, Oracle Corporation
- 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
- 	Memory: 2875986448 bytes (2742 MB) / 3584557056 bytes (3418 MB) up to 9544663040 bytes (9102 MB)
- 	CPUs: 8

**Comment by MarioAndWeegee3** [comment]
Fixed in Chicken Feathers 1.2.1
