### ISSUE TITLE
[1.15.2] Server Crash

### ISSUE THREAD

**Issue by Diamondman121314** [MarioAndWeegee3/Tool-Builder#17]
When using Tool Builder 2.0.0 on a server, it crashes. I've been using 2.0.0-alpha4 and that's worked fine. 
https://gist.github.com/Diamondman121314/d27ead916fa710dc98def92f8481239d

**Comment by AltimusX** [comment]
https://pastebin.com/MVTbNZgs

I am getting the same error.

**Comment by ghost** [comment]
+1 Getting the same error.

**Comment by MarioAndWeegee3** [comment]
I can't fix this until [this issue](https://github.com/natanfudge/artifice/issues/3) is fixed in artifice, unfortunately.

**Comment by ghost** [comment]
Thanks for the update!  I look forward to adding your mod again in the future.  It's the best of its kind!

**Comment by SDUBZ** [comment]
@MarioAndWeegee3 there is new artifice version

**Comment by MarioAndWeegee3** [comment]
Fixed in 2.0.1
