### ISSUE TITLE
1.15.2(toolbuilder-fabric-2.0.2) java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!

### ISSUE THREAD

**Issue by SDUBZ** [MarioAndWeegee3/Tool-Builder#19]
log:
https://paste.ee/p/85pwd

**Comment by MarioAndWeegee3** [comment]
delete the config file

**Comment by SDUBZ** [comment]
oh forgot to close after i tried this found out like 2 seconds after posting crash
thanks anyways man
