### ISSUE TITLE
1.14.4(fabric)client joining server causes kick from mod conflict as far as i can tell

### ISSUE THREAD

**Issue by SDUBZ** [MarioAndWeegee3/Tool-Builder#2]
as seen here https://github.com/Draylar/vanilla-toolsets/issues/12

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/MarioAndWeegee3/Tool-Builder/files/3493626/latest.log)
also happen when loading a old world of mine too @MarioAndWeegee3

**Comment by MarioAndWeegee3** [comment]
Fixed in Release 1.7.0
