### ISSUE TITLE
Unable to mine RAA ores

### ISSUE THREAD

**Issue by RViper80** [MarioAndWeegee3/Tool-Builder#9]
The tool builder pickaxes don't seem to be registering their correct mining level?

Coming up to any Randomly Adding Anything mod ore in a stone-type material, no matter what the mining level on the ore and pickaxe, results in being unable to break the ore.

Vanilla picks, ComputerCraft:Tweaked turtles and picks from the Materialization mod all work fine on those ores.

**Comment by MarioAndWeegee3** [comment]
Fixed in 1.16.5.
